# Generated by Django 5.0.4 on 2024-04-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_rename_description_drink_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='Job',
            new_name='job',
        ),
    ]
