# Generated by Django 5.0.4 on 2024-07-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_rename_job_drink_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='Job',
            new_name='Score',
        ),
    ]
