# Generated by Django 5.0.4 on 2024-10-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0009_rename_score_drink_job_remove_drink_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='job',
            new_name='score',
        ),
        migrations.AddField(
            model_name='drink',
            name='team',
            field=models.CharField(default='No Team', max_length=200),
        ),
    ]
