# Generated by Django 5.0.4 on 2024-04-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_rename_job_drink_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='job',
            new_name='Job',
        ),
    ]
