# Generated by Django 5.0.4 on 2024-04-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_rename_drinks_drink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='description',
            new_name='Job',
        ),
    ]
